### ISSUE TITLE
Option to add default values to props with validation

### ISSUE THREAD

**Issue by b44rd** [ChangJoo-Park/vue-component-generator#1]
First of all, this is a great concept! This might become very useful both for understanding how to build and use components, and in order to plan and build components very quickly. 

I think the following could make a useful improvement here; If you have selected the "Validation" option, you can also add a default value. This feature is often very useful, in order to know what the prop should contain if not provided. My suggestion, is to add another text box together with the "Required" option, that triggers the display of another text input, where you can enter a default value. This way, some props might have a default value, and some might not.

**Comment by ChangJoo-Park** [comment]
Sure. It will be change next version. Not all props need to be validated!

**Comment by b44rd** [comment]
Yes, I thought of it as some optional property, for sure. Glad to see it will become a feature! :)

**Comment by ChangJoo-Park** [comment]
@b44rd update each props has validate option or not. 
thank you :)

**Comment by b44rd** [comment]
Awesome! :)
