### ISSUE TITLE
Option to expand or minimize info column

### ISSUE THREAD

**Issue by b44rd** [ChangJoo-Park/vue-component-generator#2]
The info column seem to be taking up a bit much space in current implementation, as it contains quite a few lines of text. This makes the UI become less available then necessary. A solution to this could be to have some kind of logo there, with a "About" link, that triggers the view of the contents of this block. This way, the field doesn´t get in the way of the user interface. Another way of solving it, could be to keep the information as it is now, but move it below the user interface.

**Comment by ChangJoo-Park** [comment]
I merged [your PR](https://github.com/ChangJoo-Park/vue-component-generator/pull/3) 
It is nice solution. I am thinking about how to change it.

**Comment by b44rd** [comment]
Great! :)
