### ISSUE TITLE
The guide URL is missing

### ISSUE THREAD

**Issue by uniconstructor** [ChangJoo-Park/vue-component-generator#5]
Hello.
Tooltip at the bottom of [example page](https://changjoo-park.github.io/vue-component-generator/) says:

> Vue Component Generator was created for the purpose of describing the vue component. Please **refer to the guide** because some parts are not included.

The question is: **where is the guide**? :)
Can you post a url to this guide? 

Thank you.

**Comment by uniconstructor** [comment]
And maybe I am confused about all of this, so can you clarify: what guide are you talking about: [official Vue.js guide](https://vuejs.org/v2/guide/) or guide for this component generator?

**Comment by ChangJoo-Park** [comment]
Hello @uniconstructor It is Official Vue.js guide. If you click vue icon in https://changjoo-park.github.io/vue-component-generator/  It will make you see a official guide

**Comment by uniconstructor** [comment]
Sorry, I'm just didn't noticed that the vue icons inside generator sections is a links. 
Now generator interface looks much more friendly for me. 
Thank you for the clarification.
